version: "3"

services:
  chowdown:
    image: jekyll/jekyll:3.8
    restart: always
    container_name: chowdown
    command: jekyll serve --force_polling
    ports:
      - "4000:4000"
    volumes:
      - $PWD:/srv/jekyll
