version: "3"

services:
  chowdown:
    image: jekyll/jekyll
    restart: always
    container_name: chowdown
    command: jekyll serve --force_polling
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - _components:/srv/jekyll/_components
      - _images:/srv/jekyll/_images
      - _posts:/srv/jekyll/_posts
      - _recipes:/srv/jekyll/_recipes
