version: "3"

services:
  chowdown:
    image: jekyll/jekyll
    restart: always
    container_name: chowdown
    command: jekyll serve --force_polling
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
