version: "3"

services:
  chowdown:
    image: jekyll/jekyll:3.8
    restart: always
    container_name: chowdown
    command: jekyll serve --watch --drafts
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
